spring:
  jpa:
    show-sql: false
    hibernate:      ddl-auto: create-drop

---
spring:
  profiles: development
  datasource:
    url: jdbc:mysql://localhost:3306/spring_security
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: abc123abc
  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect
    hibernate:
      ddl-auto: update
